{
 "title": "Phân tích thời gian",
 "description": "8. Phân tích thời gian. \nMục đích: Theo dõi xu hướng và biến động của các chỉ số nhân sự theo thời gian.\n8.a Lương trung bình của nhân viên qua các năm \n8.b Tỷ lệ lương hàng năm\n8.c số giờ làm trung bình theo quý\n8.d Biến động giờ làm thêm theo tháng\n",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "8.d Biến động giờ làm thêm theo tháng",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    d.year,\r\n    d.month,\r\n    SUM(fa.overtime_hours) AS total_overtime_hours\r\nFROM \r\n    fact_attendance fa\r\nJOIN \r\n    dim_date d ON fa.date_sk = d.date_sk\r\nGROUP BY \r\n    d.year, d.month\r\nORDER BY \r\n    d.year, d.month;"
    }
   ]
  },
  {
   "title": "8.c số giờ làm trung bình theo quý",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    d.year,\r\n    d.quarter,\r\n    ROUND(AVG(fa.hours_worked), 2) AS avg_hours_worked\r\nFROM \r\n    fact_attendance fa\r\nJOIN \r\n    dim_date d ON fa.date_sk = d.date_sk\r\nGROUP BY \r\n    d.year, d.quarter\r\nORDER BY \r\n    d.year, d.quarter;"
    }
   ]
  },
  {
   "title": "8.b Tỷ lệ lương hàng năm ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "WITH yearly_salary AS (\r\n    SELECT \r\n        year,\r\n        ROUND(AVG(total_salary), 2) AS avg_salary\r\n    FROM \r\n        fact_salary fs\r\n    JOIN \r\n        dim_date d ON fs.date_sk = d.date_sk\r\n    GROUP BY \r\n        year\r\n)\r\nSELECT \r\n    curr.year,\r\n    curr.avg_salary AS current_year_salary,\r\n    prev.avg_salary AS previous_year_salary,\r\n    ROUND((curr.avg_salary - prev.avg_salary) * 100.0 / prev.avg_salary, 2) AS salary_growth_rate\r\nFROM \r\n    yearly_salary curr\r\nLEFT JOIN \r\n    yearly_salary prev ON curr.year = prev.year + 1;"
    }
   ]
  },
  {
   "title": "8.a Lương trung bình của nhân viên qua các năm ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    d.year,\r\n    ROUND(AVG(fs.total_salary), 2) AS avg_salary\r\nFROM \r\n    fact_salary fs\r\nJOIN \r\n    dim_date d ON fs.date_sk = d.date_sk\r\nGROUP BY \r\n    d.year\r\nORDER BY \r\n    d.year;"
    }
   ]
  }
 ]
}