{
 "title": "Phân tích công tác",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 5 nhân viên có nhiều chuyến công tác nhất",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT TOP 5\r\n    employee_name,\r\n    department_name,\r\n    position_name,\r\n    COUNT(*) AS total_trips,\r\n    SUM(trip_duration) AS total_days_on_trip\r\nFROM fact_work_trips\r\nWHERE status = 'Hoàn thành'\r\nGROUP BY employee_name, department_name, position_name\r\nORDER BY total_trips DESC, total_days_on_trip DESC;\r\n"
    }
   ]
  },
  {
   "title": "Phân tích theo mục đích công tác",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    purpose,\r\n    COUNT(*) AS trip_count,\r\n    COUNT(DISTINCT destination) AS distinct_destinations,\r\n    AVG(trip_duration) AS avg_duration\r\nFROM fact_work_trips\r\nWHERE status = 'Hoàn thành'\r\nGROUP BY purpose\r\nORDER BY trip_count DESC;"
    }
   ]
  },
  {
   "title": "Tổng thời gian công tác theo phòng ban",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    department_name,\r\n    COUNT(*) AS total_trips,\r\n    SUM(trip_duration) AS total_day\r\nFROM fact_work_trips\r\nWHERE status = 'Hoàn thành'\r\nGROUP BY department_name\r\nORDER BY total_day DESC;"
    }
   ]
  },
  {
   "title": "Điểm đến công tác phổ biến ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT TOP 10\r\n    destination,\r\n    COUNT(*) AS trip_count,\r\n    COUNT(DISTINCT employee_name) AS distinct_employees,\r\n    AVG(trip_duration) AS avg_duration\r\nFROM fact_work_trips\r\nWHERE status = 'Hoàn thành'\r\nGROUP BY destination\r\nORDER BY trip_count DESC;"
    }
   ]
  },
  {
   "title": "Xu hướng công tác theo tháng",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    dd.year,\r\n    dd.month,\r\n    COUNT(*) AS trip_count,\r\n    SUM(fwt.trip_duration) AS total_days\r\nFROM fact_work_trips fwt\r\nJOIN dim_date dd ON fwt.start_date_sk = dd.date_sk\r\nWHERE fwt.status = 'Hoàn thành'\r\nGROUP BY dd.year, dd.month\r\nORDER BY dd.year, dd.month;"
    }
   ]
  },
  {
   "title": "Thời gian công tác theo vị trí/chức vụ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    position_name,\r\n    COUNT(*) AS trip_count,\r\n    AVG(trip_duration) AS avg_duration\r\nFROM fact_work_trips\r\nWHERE status = N'Hoàn thành'\r\nGROUP BY position_name\r\nORDER BY avg_duration;"
    }
   ]
  }
 ]
}