{
 "title": "Phân tích hiệu suất làm việc của nhân viên",
 "description": "Mục đích: Đánh giá hiệu suất làm việc thông qua các chỉ số như số giờ làm việc, đi muộn, làm thêm giờ, và rời sớm.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Thống kê hiệu suất theo phòng ban",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    department_name,\r\n    COUNT(DISTINCT employee_name) AS employee_count,\r\n    ROUND(AVG(hours_worked), 2) AS avg_hours_per_day,\r\n    SUM(CAST(is_late AS INT)) * 100.0 / COUNT(*) AS late_percentage,\r\n    SUM(overtime_hours) AS total_overtime\r\nFROM fact_attendance\r\nGROUP BY department_name\r\nORDER BY avg_hours_per_day DESC;"
    }
   ]
  },
  {
   "title": "Top 5 nhân viên có tổng số giờ làm việc nhiều nhất trong năm 2025",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT TOP 5\r\n    employee_name,\r\n    department_name,\r\n    SUM(hours_worked) AS total_hours_worked,\r\n    COUNT(*) AS working_days\r\nFROM fact_attendance fa\r\nINNER JOIN dim_date dd ON fa.date_sk = dd.date_sk\r\nWHERE dd.year = 2025 \r\nGROUP BY employee_name, department_name\r\nORDER BY total_hours_worked DESC;"
    }
   ]
  },
  {
   "title": "Top 5 nhân viên có tổng giờ làm thêm cao nhất",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT TOP 5\r\n    employee_name,\r\n    department_name,\r\n    SUM(overtime_hours) AS total_overtime,\r\n    ROUND(AVG(overtime_hours), 2) AS avg_overtime_per_day\r\nFROM fact_attendance\r\nWHERE overtime_hours > 0\r\nGROUP BY employee_name, department_name\r\nORDER BY total_overtime DESC;"
    }
   ]
  },
  {
   "title": "Top 3 phòng ban có tỷ lệ đi muộn cao nhất ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT TOP 3\r\n    department_name,\r\n    COUNT(*) AS total_days,\r\n    SUM(CAST(is_late AS INT)) AS late_days,\r\n    ROUND(SUM(CAST(is_late AS FLOAT)) * 100 / COUNT(*), 2) AS late_percentage\r\nFROM fact_attendance\r\nGROUP BY department_name\r\nORDER BY late_percentage DESC;"
    }
   ]
  }
 ]
}