{
 "title": "Phân tích lương và phúc lợi",
 "description": "Hiểu rõ chi phí lương, phụ cấp, và khấu trừ để tối ưu hóa ngân sách và đảm bảo công bằng trong chính sách lương.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Phân tích lương theo độ tuổi giới tính ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    de.gender,\r\n    CASE \r\n        WHEN de.age < 25 THEN N'Dưới 25'\r\n        WHEN de.age BETWEEN 25 AND 35 THEN '25-35'\r\n        WHEN de.age BETWEEN 36 AND 45 THEN '36-45'\r\n        WHEN de.age > 45 THEN N'Trên 45'\r\n    END AS age_group,\r\n    AVG(fs.total_salary) AS avg_salary,\r\n    COUNT(*) AS employee_count\r\nFROM fact_salary fs\r\nINNER JOIN dim_employees de ON fs.employee_sk = de.employee_sk\r\nWHERE fs.payment_status = N'Đã thanh toán'\r\nGROUP BY \r\n    de.gender,\r\n    CASE \r\n        WHEN de.age < 25 THEN N'Dưới 25'\r\n        WHEN de.age BETWEEN 25 AND 35 THEN '25-35'\r\n        WHEN de.age BETWEEN 36 AND 45 THEN '36-45'\r\n        WHEN de.age > 45 THEN N'Trên 45'\r\n    END\r\nORDER BY age_group, gender;"
    }
   ]
  },
  {
   "title": "Chi tiết theo từng nhân viên",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    employee_name,\r\n    department_name,\r\n    position_name,\r\n    basic_salary,\r\n    allowance,\r\n    deductions,\r\n    total_salary,\r\n    ROUND(basic_salary * 100.0 / total_salary, 2) AS basic_salary_percentage,\r\n    ROUND(allowance * 100.0 / total_salary, 2) AS allowance_percentage,\r\n    ROUND(deductions * 100.0 / total_salary, 2) AS deductions_percentage\r\nFROM fact_salary\r\nWHERE total_salary > 0 AND payment_status = N'Đã thanh toán'\r\nORDER BY basic_salary_percentage DESC;"
    }
   ]
  },
  {
   "title": "Tỷ lệ lương cơ bản/tổng lương theo phòng ban",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    department_name,\r\n    AVG(basic_salary) AS avg_basic,\r\n    AVG(total_salary) AS avg_total,\r\n    ROUND(AVG(basic_salary * 100.0 / total_salary), 2) AS basic_salary_ratio,\r\n    ROUND(AVG(allowance * 100.0 / total_salary), 2) AS allowance_ratio,\r\n    ROUND(AVG(deductions * 100.0 / total_salary), 2) AS deductions_ratio\r\nFROM fact_salary\r\nWHERE total_salary > 0 AND payment_status = N'Đã thanh toán'\r\nGROUP BY department_name\r\nORDER BY basic_salary_ratio DESC;"
    }
   ]
  },
  {
   "title": "Top 5 nhân viên có tổng lương thấp nhất",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT TOP 5\r\n    employee_name,\r\n    department_name,\r\n    position_name,\r\n    total_salary,\r\n    basic_salary,\r\n    allowance,\r\n    deductions\r\nFROM fact_salary\r\nWHERE payment_status = N'Đã thanh toán'\r\nORDER BY total_salary ASC;"
    }
   ]
  },
  {
   "title": "Top 5 nhân viên có tổng lương cao nhất",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT TOP 5\r\n    employee_name,\r\n    department_name,\r\n    position_name,\r\n    total_salary,\r\n    basic_salary,\r\n    allowance,\r\n    deductions,\r\n    ROUND((total_salary * 100.0) / (SELECT MAX(total_salary) FROM fact_salary), 2) AS salary_percentage\r\nFROM fact_salary\r\nWHERE payment_status = N'Đã thanh toán'\r\nORDER BY total_salary DESC;"
    }
   ]
  },
  {
   "title": "Lương trung bình theo phòng ban và vị trí",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    department_name,\r\n    position_name,\r\n    COUNT(DISTINCT employee_name) AS employee_count,\r\n    AVG(basic_salary) AS avg_basic_salary,\r\n    AVG(allowance) AS avg_allowance,\r\n    AVG(deductions) AS avg_deductions,\r\n    AVG(total_salary) AS avg_total_salary\r\nFROM fact_salary\r\nWHERE payment_status = N'Đã thanh toán' \r\nGROUP BY department_name, position_name\r\nORDER BY department_name, avg_total_salary DESC;"
    }
   ]
  }
 ]
}