{
 "title": "Phân tích theo đặc điểm nhân khẩu học",
 "description": "9. Phân tích theo đặc điểm nhân khẩu học\n--Mục đích: Hiểu sự khác biệt giữa các nhóm nhân viên dựa trên giới tính, độ tuổi, hoặc các đặc điểm khác.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tỷ lệ nghỉ việc theo nhóm tuổi",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN age BETWEEN 18 AND 30 THEN '18-30'\r\n        WHEN age BETWEEN 31 AND 45 THEN '31-45'\r\n        ELSE '46+'\r\n    END AS age_group,\r\n    COUNT(*) AS total_employees,\r\n    SUM(CASE WHEN contract_end_date < GETDATE() THEN 1 ELSE 0 END) AS resigned_count,  \r\n    ROUND(SUM(CASE WHEN contract_end_date < GETDATE() THEN 1.0 ELSE 0 END) * 100.0 / COUNT(*), 2) AS resignation_rate \r\nFROM\r\n    dim_employees\r\nGROUP BY\t\r\n    CASE\r\n        WHEN age BETWEEN 18 AND 30 THEN '18-30'\r\n        WHEN age BETWEEN 31 AND 45 THEN '31-45'\r\n        ELSE '46+'\r\n    END;"
    }
   ]
  },
  {
   "title": "Tuổi trung bình của nhân viên theo phòng ban",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    e.department_name,\r\n    ROUND(AVG(e.age), 0) AS avg_age\r\nFROM \r\n    dim_employees e\r\nGROUP BY \r\n    e.department_name\r\nORDER BY \r\n    avg_age DESC;"
    }
   ]
  },
  {
   "title": "Phân bổ nhân viên theo độ tuổi và phòng ban",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    e.department_name,\r\n    CASE \r\n        WHEN e.age BETWEEN 18 AND 30 THEN '18-30'\r\n        WHEN e.age BETWEEN 31 AND 45 THEN '31-45'\r\n        ELSE '46+'\r\n    END AS age_group,\r\n    COUNT(*) AS employee_count\r\nFROM \r\n    dim_employees e\r\nGROUP BY \r\n    e.department_name,\r\n    CASE \r\n        WHEN e.age BETWEEN 18 AND 30 THEN '18-30'\r\n        WHEN e.age BETWEEN 31 AND 45 THEN '31-45'\r\n        ELSE '46+'\r\n    END\r\nORDER BY \r\n    e.department_name,\r\n    age_group;"
    }
   ]
  },
  {
   "title": "Số ngày nghỉ phép trung bình theo giới tính",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    e.gender,\r\n    ROUND(AVG(flb.used_leave_days), 2) AS avg_leave_days\r\nFROM \r\n    fact_leave_balance flb\r\nJOIN \r\n    dim_employees e ON flb.employee_sk = e.employee_sk\r\nGROUP BY \r\n    e.gender;"
    }
   ]
  },
  {
   "title": "Số giờ làm việc trung bình theo nhóm tuổi",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    CASE \r\n        WHEN age BETWEEN 18 AND 25 THEN '18-25'\r\n        WHEN age BETWEEN 26 AND 35 THEN '26-35'\r\n        WHEN age BETWEEN 36 AND 45 THEN '36-45'\r\n        ELSE '46+'\r\n    END AS age_group,\r\n    ROUND(AVG(fa.hours_worked), 2) AS avg_hours_worked\r\nFROM \r\n    fact_attendance fa\r\nJOIN \r\n    dim_employees e ON fa.employee_sk = e.employee_sk\r\nGROUP BY \r\n    CASE \r\n        WHEN age BETWEEN 18 AND 25 THEN '18-25'\r\n        WHEN age BETWEEN 26 AND 35 THEN '26-35'\r\n        WHEN age BETWEEN 36 AND 45 THEN '36-45'\r\n        ELSE '46+'\r\n    END\r\nORDER BY \r\n    avg_hours_worked DESC;"
    }
   ]
  },
  {
   "title": "Phân tích lương theo giới tính và theo độ tuổi ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "-- Tạo nhóm tuổi\r\nWITH employee_age_groups AS (\r\n    SELECT \r\n        employee_sk,\r\n        gender,\r\n        CASE \r\n            WHEN age BETWEEN 18 AND 25 THEN '18-25'\r\n            WHEN age BETWEEN 26 AND 35 THEN '26-35'\r\n            WHEN age BETWEEN 36 AND 45 THEN '36-45'\r\n            WHEN age BETWEEN 46 AND 55 THEN '46-55'\r\n            ELSE '56+'\r\n        END AS age_group\r\n    FROM \r\n        dim_employees\r\n)\r\n-- Tính lương trung bình theo nhóm\r\nSELECT \r\n    eag.gender,\r\n    eag.age_group,\r\n    ROUND(AVG(fs.total_salary), 2) AS avg_salary\r\nFROM \r\n    fact_salary fs\r\nJOIN \r\n    employee_age_groups eag ON fs.employee_sk = eag.employee_sk\r\nGROUP BY \r\n    eag.gender, eag.age_group\r\nORDER BY \r\n    eag.gender, eag.age_group;"
    }
   ]
  },
  {
   "title": "Phân tích giờ làm thêm theo giới tính và vị trí",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    e.gender,\r\n    e.position_name,\r\n    SUM(fr.registration_duration) AS total_overtime_hours\r\nFROM \r\n    fact_registrations fr\r\nJOIN \r\n    dim_employees e ON fr.employee_sk = e.employee_sk\r\nWHERE \r\n    fr.registration_type = 'Làm thêm'\r\nGROUP BY \r\n    e.gender, e.position_name\r\nORDER BY \r\n    total_overtime_hours DESC;"
    }
   ]
  },
  {
   "title": "Tỷ lệ khen thưởng theo giới tính",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    e.gender,\r\n    COUNT(fd.decision_sk) AS total_rewards,\r\n    ROUND(COUNT(fd.decision_sk) * 100.0 / SUM(COUNT(fd.decision_sk)) OVER (), 2) AS reward_percentage\r\nFROM \r\n    fact_decision fd\r\nJOIN \r\n    dim_employees e ON fd.employee_sk = e.employee_sk\r\nWHERE \r\n    fd.decision_type = 'Khen thưởng'\r\nGROUP BY \r\n    e.gender;"
    }
   ]
  }
 ]
}