{
 "title": "Phân tích đăng ký (nghỉ phép, làm thêm, công tác)",
 "description": "Mục đích: Quản lý các yêu cầu đăng ký của nhân viên để đảm bảo quy trình phê duyệt hợp lý",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "top 5 phòng ban có số đăng ký cao nhất ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT TOP 5\r\n    department_name,\r\n    COUNT(registration_sk) AS total_registrations\r\nFROM \r\n    fact_registrations\r\nGROUP BY \r\n    department_name\r\nORDER BY \r\n    total_registrations DESC;"
    }
   ]
  },
  {
   "title": "thống kê đăng ký theo trạng thái  duyệt",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    status,\r\n    registration_type,\r\n    COUNT(*) AS count,\r\n    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY registration_type), 2) AS percentage\r\nFROM \r\n    fact_registrations\r\nGROUP BY \r\n    registration_type, \r\n    status;"
    }
   ]
  },
  {
   "title": "Xu hướng đăng ký theo thời gian",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    d.year,\r\n    d.month,\r\n    r.registration_type,\r\n    COUNT(r.registration_sk) AS total_registrations\r\nFROM \r\n    fact_registrations r\r\nJOIN \r\n    dim_date d ON r.request_date_sk = d.date_sk\r\nGROUP BY \r\n    d.year, \r\n    d.month, \r\n    r.registration_type\r\nORDER BY \r\n    d.year, \r\n    d.month, total_registrations;"
    }
   ]
  },
  {
   "title": "Tỷ lệ duyệt đăng ký theo loại",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    registration_type,\r\n    COUNT(*) AS total_registrations,\r\n    SUM(CASE WHEN status = N'Đã duyệt' THEN 1 ELSE 0 END) AS approved_count,\r\n    ROUND(\r\n        SUM(CASE WHEN status = N'Đã duyệt' THEN 1.0 ELSE 0 END) / COUNT(*) * 100, \r\n        2\r\n    ) AS approval_rate_percentage\r\nFROM \r\n    fact_registrations\r\nGROUP BY \r\n    registration_type\r\nORDER BY \r\n    approval_rate_percentage DESC;"
    }
   ]
  },
  {
   "title": "Số lượng đăng ký theo loại của từng nhân viên",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    e.full_name,\r\n    r.registration_type,\r\n    COUNT(r.registration_sk) AS total_registrations\r\nFROM \r\n    fact_registrations r\r\nJOIN \r\n    dim_employees e ON r.employee_sk = e.employee_sk\r\nGROUP BY \r\n    e.full_name, \r\n    r.registration_type\r\nORDER BY \r\n    e.full_name, \r\n    total_registrations DESC;"
    }
   ]
  },
  {
   "title": "Số lượng đăng ký theo loại và phòng ban",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    r.department_name,\r\n    r.registration_type,\r\n    COUNT(r.registration_sk) AS total_registrations\r\nFROM \r\n    fact_registrations r\r\nGROUP BY \r\n    r.department_name, \r\n    r.registration_type\r\nORDER BY \r\n    r.department_name, \r\n    total_registrations DESC;"
    }
   ]
  },
  {
   "title": " số gio làm thêm trung bình được duyệt",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "hrms_warehouse",
     "rawSql": "SELECT \r\n    AVG(registration_duration) AS avg_overtime_hours\r\nFROM \r\n    fact_registrations\r\nWHERE \r\n    registration_type = 'Làm thêm' \r\n    AND status = 'Đã duyệt';"
    }
   ]
  }
 ]
}